schema_version: 1

context:
  name: keyrings.artifacts
  version: 0.4.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/keyrings_artifacts-${{ version }}.tar.gz
  sha256: fbe796bc0ec7eed6c14ea7dac5fefe086429b81f338ed632000221f24b0a782a

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - keyring = keyring.cli:main

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - keyring >=16.0
    - requests >=2.20.0
    - azure-identity >=1.17.1
    - keyrings.alt >=5.0.0
    - pycryptodomex >=3.20.0

tests:
  - python:
      imports:
        - keyrings_artifacts
  - requirements:
      run:
        - pip
    script:
      - pip check
      - keyring --help

about:
  summary: Keyring backend, that automatically retrieves credentials for Azure Artifacts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jslorrma
