name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: ci

      - name: Build package
        run: pixi run -e dev build-wheel

      - name: Publish to PyPI
        run: |
          pixi run -e ci  twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  release:
    name: Create Release
    needs: [build-and-publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          pattern: keyrings_artifacts-*
          merge-multiple: true

      - name: Push v${{ github.event.release.tag_name }} tag
        run: |
          git tag v${{ github.event.release.tag_name }}
          git push origin v${{ github.event.release.tag_name }}

      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true
      #     tag_name: v${{ github.event.release.tag_name }}
      #     draft: true
      #     files: keyrings_artifacts-*
